# Header
menu:
  主页: /
  归类: /archives
  关于: /about
rss: /atom.xml

# Content
#  查看更多 Read More
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
# 归类
- category
# 标签
- tag
# 标签云
- tagcloud
- archive
- recent_posts
# 浏览量统计
- popular_posts
# 友情链接
- links

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
# 依据什么来分类（此处以月份来分类）
archive_type: 'monthly'
# 显示当前分类的博客条数
show_count: true

# Miscellaneous
# ico图片
favicon: http://ohecg7vrp.bkt.clouddn.com/favicon.ico
google_analytics:
twitter:
google_plus:
fb_admins:
fb_app_id:


# 是否开启打赏功能
donate: true
# 打赏文案
donate_message: 欣赏此文？求鼓励，求支持！